name: Build Release

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-release:
    if: ${{ github.repository == vars.SOURCE_REPO_NAME }}
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Build Project
        run: make

      - name: Create Release
        uses: actions/upload-artifact@v4
        with:
          name: glados-v1.0.${{ github.run_number }}
          path: ./glados
