name: Build

on:
  pull_request:
    branches: [main]

jobs:
  check-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      
      - name: Compile the project
        run: make
