name: Build

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths-ignore:
      - "ga-ignore/**"

jobs:
  check-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      
      - name: Compile the project
        run: make
