name: Build

on:
  workflow_run:
    workflows: ["Formatting"]
    types:
      - completed

jobs:
  check-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      
      - name: Compile the project
        run: make
