name: Formatting

on:
  pull_request:
    branches: [main]

env:
  REPORT_FILE: "coding-style-reports.log"

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    
    container:
      image: ghcr.io/epitech/coding-style-checker:latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      
      # (Epitech's coding style checker)
      - name: Run lambdananas
        run: |
          lambdananas . > $REPORT_FILE
          if [ -s $REPORT_FILE ]; then
            cat $REPORT_FILE
            exit 1
          fi
