name: Push Mirror

on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  MIRROR_URL: "git@github.com:EpitechPromo2027/B-FUN-500-PAR-5-2-glados-marius.rousset.git"

jobs:
  push-to-mirror:
    if: ${{ github.repository == vars.SOURCE_REPO_NAME }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # all commits, not just the last one

      - name: Install git-filter-repo
        run: sudo apt-get install -y git-filter-repo

      - name: Remove the workflows # to prevent them from being called on the epitech repo
        run: |
          git filter-repo --path .github/workflows/ --invert-paths
          git push --force
      
      - name: Ls to check if the workflows were deleted
        run : |
          ls -R

      - name: Mirror the repo
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.MIRROR_URL }}
          ssh_private_key: ${{ secrets.SSH_KEY }}
