name: Push Mirror

on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  MIRROR_URL: "git@github.com:EpitechPromo2027/B-FUN-500-PAR-5-2-glados-marius.rousset.git"

jobs:
  push-to-mirror:
    if: github.repository == vars.SOURCE_REPO_NAME

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # all commits, not just the last one

      - name: Mirror the repo
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.MIRROR_URL }}
          ssh_private_key: ${{ secrets.SSH_KEY }}
