name: Functionnal Tests

on:
  workflow_run:
    workflows: ["Build"]

jobs:
  check-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Run the unit-tests
        run: make unit-tests
      
      - name: Run the functionnal-tests
        run: make functionnal-tests
