name: Functionnal Tests

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  check-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Run the unit-tests
        run: make unit-tests
      
      - name: Run the functionnal-tests
        run: make functionnal-tests
