name: Unit Tests

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths-ignore:
      - "ga-ignore/**"

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Run the unit-tests
        run: make unit-tests
